#!/bin/bash
# Cyber Launcher をログイン時に自動起動する LaunchAgent を登録する。
set -euo pipefail

LABEL="com.cyber-launcher"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SUPPORT_DIR="$HOME/Library/Application Support/CyberLauncher"
LAUNCH_SH="$SUPPORT_DIR/launch.sh"
BIN="$REPO_ROOT/.build/release/CyberLauncher"
PLIST_DEST="$HOME/Library/LaunchAgents/${LABEL}.plist"
TEMPLATE="$REPO_ROOT/scripts/com.cyber-launcher.plist.template"
GUI_DOMAIN="gui/$(id -u)"

if [[ ! -x "$REPO_ROOT/start.sh" ]]; then
  chmod +x "$REPO_ROOT/start.sh"
fi

cd "$REPO_ROOT"
swift build -c release

mkdir -p "$SUPPORT_DIR"
cat > "$LAUNCH_SH" <<EOF
#!/bin/bash
# Generated by install-launch-agent.sh — do not edit by hand.
exec "$BIN"
EOF
chmod +x "$LAUNCH_SH"

if [[ ! -f "$TEMPLATE" ]]; then
  echo "error: template not found: $TEMPLATE" >&2
  exit 1
fi

mkdir -p "$HOME/Library/LaunchAgents"
sed \
  -e "s|__LAUNCH_SH__|${LAUNCH_SH}|g" \
  -e "s|__SUPPORT_DIR__|${SUPPORT_DIR}|g" \
  "$TEMPLATE" > "$PLIST_DEST"

# 既に登録済みなら一度外す
if launchctl print "$GUI_DOMAIN/$LABEL" &>/dev/null; then
  launchctl bootout "$GUI_DOMAIN" "$PLIST_DEST" 2>/dev/null || true
fi

launchctl bootstrap "$GUI_DOMAIN" "$PLIST_DEST"

"$REPO_ROOT/scripts/install-macos-shortcut.sh" 2>/dev/null || true

echo "Installed: $PLIST_DEST"
echo "  Launcher: $LAUNCH_SH"
echo "  Repo:     $REPO_ROOT"
echo "  Logs:    /tmp/cyber-launcher.log"
echo "  Errors:  /tmp/cyber-launcher.err"
echo ""
echo "Status:"
launchctl print "$GUI_DOMAIN/$LABEL" 2>/dev/null | head -20 || launchctl list | grep "$LABEL" || true
echo ""
echo "ショートカット (⌘+Shift+L) が競合する場合:"
echo "  システム設定 → キーボード → キーボードショートカット → サービス"
echo "  で Toggle Cyber Launcher に ⌘+Shift+L を割り当ててください。"
echo "  再起動: launchctl kickstart -k gui/$(id -u)/com.cyber-launcher"
